version: "3.9"
services:
  selenium-hub:
    image: selenium/hub:4.12.1
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome-node-1:
    image: selenium/node-chrome:4.12.1
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    shm_size: 2g

  chrome-node-2:
    image: selenium/node-chrome:4.12.1
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    shm_size: 2g

  chrome-node-3:
    image: selenium/node-chrome:4.12.1
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    shm_size: 2g

  firefox:
    image: selenium/node-firefox:4.12.1
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    shm_size: 2g

  task-runner:
    build:
      context: .
    environment:
      - GRID_URL=http://selenium-hub:4444/wd/hub
    depends_on:
      - selenium-hub
